additionalProperties:
  pubName: mattermost_api
  pubAuthor: Jeff Mikels
  pubAuthorEmail: jeffmikels@gmail.com
  pubDescription: desc
  pubHomepage: homepage
  pubLibrary: mattermost.api
  pubVersion: 0.1.0
  useEnumExtension: true
  apiClientName: MattermostApiClient # takes precedent over prefix/suffix defaults to ApiClient if not specified
  apiNamePrefix: Mattermost
  apiNameSuffix: Api
  modelNamePrefix: Mm
  modelNameSuffix:
  
readmeName: GENERATED_README

templateDir: openapi_mattermost_templates
# templateDir: /Users/Jeff/Development/@Dart/openapi-working/openapi-generator/modules/openapi-generator/src/main/resources/dart2
skipValidateSpec: false
skipOverwrite: false

debugModels: false
debugOperations: false
org.openapitools.codegen.utils.oncelogger.enabled: true
verbose: false
